### ISSUE TITLE
Resize items of the list

### ISSUE THREAD

**Issue by andreddie81** [mobiten/flutter_staggered_animations#2]
I have tried to use your example in 2 ways:

1. using the example of the ListView but on an horizontal-scroll list
2. using the example of the GridView as it is

In both of the cases, I have tried in many ways to resize width and/or height of the elements of myChildList...however, in both cases it has not been possible, they keep showing taking the full height in the case of the ListView, and in some sort of pre-defined height and width for the GridView.

Can you help with that? how to achieve the desired width and height of the child items?

**Comment by CallMeSH** [comment]
Hello @andreddie81,

Would it be possible for you to provide some code for us to reproduce your problem?

Thanks!

**Comment by andreddie81** [comment]
sure, for example in this piece of code, I am trying to force a ridiculously small value for height, to check if the elements of the grid resize. However they are always the same size:

```
class AvailableCards extends StatelessWidget {
  final List<Widget> availableCardsList;

  AvailableCards(this.availableCardsList);

  @override
  Widget build(BuildContext context) {
    int columnCount = 4;
    var w = MediaQuery.of(context).size.width;
    var h = MediaQuery.of(context).size.height;
    return Scaffold(
      body: AnimationLimiter(
        child: GridView.count(
          crossAxisCount: columnCount,
          children: List.generate(
            availableCardsList.length,
            (int index) {
              return Container(
                height: 10, // FORCING HEIGHT OF CHILDREN HERE
                child: AnimationConfiguration.staggeredList(
                  position: index,
                  duration: const Duration(milliseconds: 375),
                  child: ScaleAnimation(
                    child: FadeInAnimation(
                      child: availableCardsList[index],
                    ),
                  ),
                ),
              );
            },
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.arrow_back),
        backgroundColor: Colors.grey,
        onPressed: () => Navigator.pop(context),
      ),
    );
  }
}
```

I have to say that i am not sure where to add the value of the height so the elements of the grid take it.

I also found out by the way that, in the example of the gridView, this line gives error as the columncount is not recognized as a named parameter: 

```
....
columnCount: columnCount,
....
```

Hope that helps.

**Comment by CallMeSH** [comment]
Hello again @andreddie81,

None of the issues are bugs, so that's good news!

Regarding the fact that you can't change the size of the item displayed in your grid:
This is because you use `GridView` which uses a `childAspectRatio` parameter to configure its children's size. The Widget's size is ignored in a `GridView` in favour of the aspect ratio.
To fix this, if all your elements have the same size, just pick the right aspect ratio, otherwise you should use a different widget than `GridView`.
The library is technically compatible with any widget you'll pick.

Our example project was misleading by specifying sizes that were not honoured by the `GridView`. I have updated the code on master.

Secondly regarding the `columnCount`, this is a from a typo in our README that suggested you use `AnimationConfiguration.staggeredList` instead of `AnimationConfiguration.staggeredGrid`. I also fixed it on master.

I hope this will help you!

**Comment by andreddie81** [comment]
aha ok that was the reason, ok understood, and thanks for the explanation!.
