### ISSUE TITLE
Invalid when the list length is variable

### ISSUE THREAD

**Issue by q876625596** [mobiten/flutter_staggered_animations#8]
I changed itemCount: 100 to itemCount: dataList.length,
Then get the list data through the network and change the dataList, this animation is invalid

**Comment by MrLepage** [comment]
Hello,
Could you be more precise, provide a sample code as well as a video of the problem you have ?

**Comment by q876625596** [comment]
``` dart
AnimationLimiter(
    child: ListView.builder(
                 padding: const EdgeInsets.all(8.0),
                 itemCount: data.length,
                 itemBuilder: (BuildContext context, int index) {
                     return AnimationConfiguration.staggeredList(
                     position: index,
                     duration: const Duration(milliseconds: 375,),
                     child: SlideAnimation(
                         verticalOffset: 44.0,
                         child: FadeInAnimation(
                             child: ShopItemView(
                                 item: data[index],
            ),
          ),
        ),
      );
    },
  ),
),
```
This data comes from the network. When my data changes, the list animation is not displayed.

**Comment by pedromassango** [comment]
@q876625596 are you updating your widget's state?

**Comment by tpm5183** [comment]
Hi, this has happened to me as well. This is due to the AnimationLimiter class drawing the animation when it first loaded. If your list is dynamic but the content is still the same, the animation won't redraw itself because it was already done so the first time. 

I think the goal here is to redraw items regardless if they have been drawn the first time. I think this can be achieved by wrapping the AnimationLimiter class in another class which you will recall setState on for each time your list is changing. Kind of a hack, but maybe try removing the AnimationLimiter class and use 

`ListView.builder(
                 padding: const EdgeInsets.all(8.0),
                 itemCount: data.length,
                 itemBuilder: (BuildContext context, int index) {
                     return AnimationConfiguration.staggeredList(
                     position: index,
                     duration: const Duration(milliseconds: 375,),
                     child: SlideAnimation(
                         verticalOffset: 44.0,
                         child: FadeInAnimation(
                             child: ShopItemView(
                                 item: data[index],
            ),
          ),
        ),
      );
    },
  )`

and see if you like the results. That is what I have done for my grid view.

**Comment by q876625596** [comment]
> @ q876625596您是否正在更新小部件的状态？

Yes i am updating dynamically

**Comment by MrLepage** [comment]
Hello there, 

As @tpm5183 said, the `AnimationLimiter` prevents the list to animate again if your list is dynamic and your widget is rebuilt.

You can provide a new key to the `AnimationLimiter` widget each time you want the animation to be launched again.
